---
title: "Publications"
output: html_document
csl: apa.csl
page-layout: full
title-block-banner: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
source("../functions_references.R")
```

## First author papers (open access)

```{r first author papers, echo = FALSE, results='asis'}
keys_first <- c("Kavelaars2020", 
                "Kavelaars2020a", 
                "Kavelaars2021", 
                "Kavelaars2023", 
                "Kavelaars2024"
                )


#format_apa(bib[keys_first])
refs <- unlist(lapply(1:length(keys_first), function(k) format_apa(bib[[keys_first[k]]])))
html_refs <- paste0("<p class='apa-ref'>", unlist(refs), "</p>")
cat(paste(html_refs, collapse = "\n"))

```

## Collaborations

```{r collaborations, echo = FALSE, results='asis'}
keys_collabs <- c("Scheltema2018",
                  "Schimmel2022",
                  "Brand2024",
                  "Zinzen2025",
                  "Zinzen2025a",
                  "Brand2025a",
                  "Brand2026",
                  "Brand2026a",
                  "Boekhout2026",
                  "Verhaak2026"
                  )

#format_apa(bib[keys_collabs])
refs <- unlist(lapply(1:length(keys_collabs), function(k) format_apa(bib[[keys_collabs[k]]])))
html_refs <- paste0("<p class='apa-ref'>", unlist(refs), "</p>")
cat(paste(html_refs, collapse = "\n"))
```
## Manuscripts in preparation

```{r manuscripts, echo = FALSE,  results = 'asis'}
keys_manuscripts <- c("Kavelaars2026b", 
                      "Buwalda2026", 
                      "Muradchanian2026"
                      )

refs <- unlist(lapply(1:length(keys_manuscripts), function(k) format_apa(bib[[keys_manuscripts[k]]])))
html_refs <- paste0("<p class='apa-ref'>", unlist(refs), "</p>")
cat(paste(html_refs, collapse = "\n"))
```

## Open source software
```{r citations, echo = FALSE, results='asis'}
keys_software <- c(
  "Kavelaars2020b",
  "Kavelaars2026",
  "Kavelaars2026a"
  )

refs <- unlist(lapply(1:length(keys_software), function(k) format_apa(bib[[keys_software[k]]])))
html_refs <- paste0("<p class='apa-ref'>", unlist(refs), "</p>")
cat(paste(html_refs, collapse = "\n"))
```